# Generated by Django 4.0.3 on 2022-03-13 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0001_initial'),
        ('ciudades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provinces.province', verbose_name='Provincia'),
        ),
    ]
