# Generated by Django 4.0.3 on 2022-03-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=25, verbose_name='Nombre de la Provincia')),
                ('province_state', models.BooleanField(default=False, verbose_name='Estado de la Provincia')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'provincia',
                'verbose_name_plural': 'provincias',
            },
        ),
    ]
